### ISSUE TITLE
Fails to Build on Nginx 3.1.16

### ISSUE THREAD

**Issue by kbeezie** [openresty/drizzle-nginx-module#18]
The following error is generated when trying to build /usr/ports/www/nginx-devel (version 3.1.16).

cc -c -O2 -pipe -fno-strict-aliasing -I /usr/local/include  -I src/core  -I src/event  -I src/event/modules  -I src/os/uni                  x  -I objs  -I src/http  -I src/http/modules  -I src/mail  -o objs/addon/src/ngx_http_drizzle_util.o  /var/ports/usr/ports                  /www/nginx-devel/work/chaoslawful-drizzle-nginx-module-59e12ad/src/ngx_http_drizzle_util.c
/var/ports/usr/ports/www/nginx-devel/work/chaoslawful-drizzle-nginx-module-59e12ad/src/ngx_http_drizzle_util.c: In functio                  n 'ngx_http_upstream_dbd_init_request':
/var/ports/usr/ports/www/nginx-devel/work/chaoslawful-drizzle-nginx-module-59e12ad/src/ngx_http_drizzle_util.c:437: warnin                  g: assignment from incompatible pointer type
/var/ports/usr/ports/www/nginx-devel/work/chaoslawful-drizzle-nginx-module-59e12ad/src/ngx_http_drizzle_util.c: In functio                  n 'ngx_http_upstream_dbd_connect':
/var/ports/usr/ports/www/nginx-devel/work/chaoslawful-drizzle-nginx-module-59e12ad/src/ngx_http_drizzle_util.c:584: error:                   'ngx_connection_t' has no member named 'single_connection'
**\* [objs/addon/src/ngx_http_drizzle_util.o] Error code 1

Stop in /var/ports/usr/ports/www/nginx-devel/work/nginx-1.3.16.
**\* [build] Error code 1

Stop in /var/ports/usr/ports/www/nginx-devel/work/nginx-1.3.16.
**\* [do-build] Error code 1

Stop in /usr/ports/www/nginx-devel.
**\* [build] Error code 1

Stop in /usr/ports/www/nginx-devel.

This is on a fresh jail that has not had nginx installed on it before, so no previous dist files or dependencies (/usr/ports/databases/libdrizzle was installed prior). 

I'm somewhat concerned that I'll need to stay on version 1.2 for a while, as Nginx 1.4 was just released not that long ago for both stable/dev branch, and have not seen a fix for this yet.
